name: Deploy to VPS

on:
  push:
    branches:
      #- master   # Production branch
      - staging # Staging branch

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set environment based on branch
        id: env
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/master" ]]; then
            # Master branch
            echo "environment=production" >> $GITHUB_ENV
            echo "deploy_path=/path/to/production/project" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/staging" ]]; then
            # Staging branch
            echo "environment=staging" >> $GITHUB_ENV
            echo "deploy_path=/path/to/staging/project" >> $GITHUB_ENV
          fi

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: '195.200.7.134' # $ {{ secrets.VPS_HOST }} # Same VPS for both environments, or use different secrets
          username: 'root' # $ {{ secrets.VPS_USER }}
          key: |
            -----BEGIN OPENSSH PRIVATE KEY-----
            b3BlbnNzaC1rZXktdjEAAAAACmFlczI1Ni1jdHIAAAAGYmNyeXB0AAAAGAAAABAn84WzaM
            T3e2Cnrz/nAjkoAAAAGAAAAAEAAAAzAAAAC3NzaC1lZDI1NTE5AAAAIPHiMzR3sFanRS0G
            I6XkYJaYzeuLxp4QZjtChKzlLjYtAAAAoBYbdbLjKZ0Tz7E946oD5ed/abYpetRWOuZIdQ
            GvNJuOb+z6hH5Qk6XT+XWhmYjx4f7VEuvnNxu4V5hilREXIBbjAEey9ShjnOhsaUGrISuK
            0CuLxScy/zrj5CjBO5nY6jA/bFeDVlaw7qGHmDlmAwy+pYXUKAgR1C664M6rtg/30cZAR6
            6kJ8FEcBdMlbpHpPqr/8Di6xrPNBFW5heNczI=
            -----END OPENSSH PRIVATE KEY-----
          passphrase: '#ssh88635517' #$ {{ secrets.VPS_SSH_PASSPHRASE }} # $ {{ secrets.VPS_SSH_KEY }} esse segundo no de cima
          port: 22
          script: |
            cd ${{ env.deploy_path }}               # Navigate to correct directory (staging or production)
            git pull origin ${{ env.environment }}  # Pull latest changes from corresponding branch
            echo ${{ env.environment }}
            echo ${{ env.deploy_path }}
            echo Fim.
            # npm install                            # Install dependencies (if needed)
            # npm run build                          # Build the project (if needed)
            # sudo systemctl restart nginx           # Restart Nginx to apply changes
