# {{ github.ref }} - Your branch name
# {{ github.repository }} - Your repository name

name: Deploy to VPS
on:
  push:
    branches:
      #- master   # Production branch
      - staging # Staging branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Start ssh-agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Pull latest changes from GitHub
        run: |
          echo "Pulling latest changes..."
          git remote -v
          git pull git@github.com:Augusto-DF/portfolio.git staging
        env:
          GIT_SSH_COMMAND: ssh -v

      - name: Install npm dependencies
        run: |
          if command -v npm &> /dev/null; then
            echo "Installing npm dependencies..."
            npm install
          else
            echo "npm is not installed. Please install Node.js and npm."
            exit 1
          fi

      - name: Build the project
        run: |
          if command -v yarn &> /dev/null; then
            echo "Building the project with yarn..."
            yarn build
          else
            echo "yarn is not installed. Please install Yarn."
            exit 1
          fi

      - name: Restart Nginx
        run: sudo systemctl restart nginx
