name: Staging portfolio deployment

on:
  push:
    branches: [staging]
  pull_request:
    branches: [staging]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: |
          ls -a
          # git pull origin staging
          # rm -r build/
          # yarn build

  deploy-staging:
    runs-on: ubuntu-latest
    environment:
      name: staging
    needs: [build]
    steps:
      - name: Repo Checkout
        uses: actions/checkout@v4

      - name: VPS Deployment
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: |
            ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPHiMzR3sFanRS0GI6XkYJaYzeuLxp4QZjtChKzlLjYt neoaugustocode@gmail.com
          ARGS: '-rlgoDzvc -i --delete'
          SOURCE: 'build/'
          REMOTE_HOST: '195.200.7.134'
          REMOTE_USER: 'root'
          REMOTE_PORT: 22
          TARGET: '~/../home/projects/augustocode/staging/portfolio/'
