name: Deploy to VPS

on:
  push:
    branches:
      #- master   # Production branch
      - staging # Staging branch

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set environment based on branch
        id: env
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/master" ]]; then
            # Master branch
            echo "environment=production" >> $GITHUB_ENV
            echo "deploy_path=/path/to/production/project" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/staging" ]]; then
            # Staging branch
            echo "environment=staging" >> $GITHUB_ENV
            echo "deploy_path=~/../home/projects/augustocode/staging/portfolio" >> $GITHUB_ENV
          fi

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.VPS_HOST }} # Same VPS for both environments, or use different secrets
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          passphrase: ${{ secrets.VPS_PASS }}
          port: 22
          script: |
            cd ${{ env.deploy_path }}               # Navigate to correct directory (staging or production)
            ls -a
            ${{ secrets.VPS_PASS }}
            git pull origin ${{ env.environment }}  # Pull latest changes from corresponding branch
            echo ${{ env.environment }}
            echo ${{ env.deploy_path }}
            echo Fim.
            npm install                            # Install dependencies (if needed)
            yarn build                          # Build the project (if needed)
            sudo systemctl restart nginx           # Restart Nginx to apply changes
